# coding: utf-8

"""
    LokoPay API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2024-08-22
    Contact: dev@lokopay.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from loko_client.api.customer_wallets_api import CustomerWalletsApi


class TestCustomerWalletsApi(unittest.TestCase):
    """CustomerWalletsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CustomerWalletsApi()

    def tearDown(self) -> None:
        pass

    def test_create_customer_wallet(self) -> None:
        """Test case for create_customer_wallet

        Create a customer wallet
        """
        pass


if __name__ == '__main__':
    unittest.main()
