# coding: utf-8

"""
    LokoPay API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2024-08-22
    Contact: dev@lokopay.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from loko_client.models.destination_network_detail import DestinationNetworkDetail

class TestDestinationNetworkDetail(unittest.TestCase):
    """DestinationNetworkDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DestinationNetworkDetail:
        """Test DestinationNetworkDetail
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DestinationNetworkDetail`
        """
        model = DestinationNetworkDetail()
        if include_optional:
            return DestinationNetworkDetail(
                id = '',
                destination_amount = '',
                destination_currency = '',
                destination_network = '',
                destination_network_description = '',
                destination_transaction_fee = '',
                destination_transaction_fee_currency = '',
                destination_network_fee = '',
                destination_network_fee_currency = '',
                destination_network_fee_monetary = ''
            )
        else:
            return DestinationNetworkDetail(
        )
        """

    def testDestinationNetworkDetail(self):
        """Test DestinationNetworkDetail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
