# coding: utf-8

"""
    LokoPay API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2024-08-22
    Contact: dev@lokopay.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from loko_client.models.transfer_with_native_token import TransferWithNativeToken

class TestTransferWithNativeToken(unittest.TestCase):
    """TransferWithNativeToken unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TransferWithNativeToken:
        """Test TransferWithNativeToken
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransferWithNativeToken`
        """
        model = TransferWithNativeToken()
        if include_optional:
            return TransferWithNativeToken(
                enabled = True,
                base_amount = '',
                base_network = '',
                base_currency = ''
            )
        else:
            return TransferWithNativeToken(
        )
        """

    def testTransferWithNativeToken(self):
        """Test TransferWithNativeToken"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
