# coding: utf-8

"""
    LokoPay API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2024-08-22
    Contact: dev@lokopay.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from loko_client.models.payout import Payout

class TestPayout(unittest.TestCase):
    """Payout unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Payout:
        """Test Payout
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Payout`
        """
        model = Payout()
        if include_optional:
            return Payout(
                id = '',
                object = '',
                amount = '',
                currency = '',
                description = '',
                customer = loko_client.models.payment_customer.PaymentCustomer(
                    id = '', 
                    email = '', 
                    ip_address = '', 
                    destination_address = '', 
                    destination_network = '', 
                    destination_currency = '', ),
                destination_network_details = [
                    loko_client.models.destination_network_detail.DestinationNetworkDetail(
                        id = '', 
                        destination_amount = '', 
                        destination_currency = '', 
                        destination_network = '', 
                        destination_network_description = '', 
                        destination_transaction_fee = '', 
                        destination_transaction_fee_currency = '', 
                        destination_network_fee = '', 
                        destination_network_fee_currency = '', 
                        destination_network_fee_monetary = '', )
                    ],
                blockchain_transaction_details = [
                    loko_client.models.blockchain_transaction_detail.BlockchainTransactionDetail(
                        id = '', 
                        amount = '', 
                        currency = '', 
                        network = '', 
                        address = '', 
                        tx_hash = '', 
                        confirmations = 56, 
                        block_time = 56, 
                        block_height = 56, )
                    ],
                canceled_at = 56,
                status = '',
                created_at = 56,
                obj_secret = '',
                failed_reason = '',
                transfer_with_native_token = loko_client.models.transfer_with_native_token.TransferWithNativeToken(
                    enabled = True, 
                    base_amount = '', 
                    base_network = '', 
                    base_currency = '', )
            )
        else:
            return Payout(
        )
        """

    def testPayout(self):
        """Test Payout"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
