# coding: utf-8

"""
    LokoPay API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2024-08-22
    Contact: dev@lokopay.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from loko_client.models.confirm_payout_request import ConfirmPayoutRequest

class TestConfirmPayoutRequest(unittest.TestCase):
    """ConfirmPayoutRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConfirmPayoutRequest:
        """Test ConfirmPayoutRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConfirmPayoutRequest`
        """
        model = ConfirmPayoutRequest()
        if include_optional:
            return ConfirmPayoutRequest(
                destination_network_details = [
                    loko_client.models.destination_network_detail.DestinationNetworkDetail(
                        id = '', 
                        destination_amount = '', 
                        destination_currency = '', 
                        destination_network = '', 
                        destination_network_description = '', 
                        destination_transaction_fee = '', 
                        destination_transaction_fee_currency = '', 
                        destination_network_fee = '', 
                        destination_network_fee_currency = '', 
                        destination_network_fee_monetary = '', )
                    ]
            )
        else:
            return ConfirmPayoutRequest(
        )
        """

    def testConfirmPayoutRequest(self):
        """Test ConfirmPayoutRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
