# coding: utf-8

"""
    LokoPay API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2024-08-22
    Contact: dev@lokopay.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from loko_client.api.payouts_api import PayoutsApi


class TestPayoutsApi(unittest.TestCase):
    """PayoutsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PayoutsApi()

    def tearDown(self) -> None:
        pass

    def test_cancel_payout(self) -> None:
        """Test case for cancel_payout

        Cancel payout
        """
        pass

    def test_confirm_payout(self) -> None:
        """Test case for confirm_payout

        Confirm payout
        """
        pass

    def test_create_payout(self) -> None:
        """Test case for create_payout

        Create a payment
        """
        pass

    def test_get_payout(self) -> None:
        """Test case for get_payout

        Get payout detail
        """
        pass

    def test_get_payouts(self) -> None:
        """Test case for get_payouts

        Get payouts
        """
        pass


if __name__ == '__main__':
    unittest.main()
