# coding: utf-8

"""
    LokoPay API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2024-08-22
    Contact: dev@lokopay.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from loko_client.models.general_response import GeneralResponse

class TestGeneralResponse(unittest.TestCase):
    """GeneralResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GeneralResponse:
        """Test GeneralResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GeneralResponse`
        """
        model = GeneralResponse()
        if include_optional:
            return GeneralResponse(
                status = '',
                message = '',
                token = ''
            )
        else:
            return GeneralResponse(
                status = '',
                message = '',
        )
        """

    def testGeneralResponse(self):
        """Test GeneralResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
