# coding: utf-8

"""
    LokoPay API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2024-08-22
    Contact: dev@lokopay.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from loko_client.api.networkfees_api import NetworkfeesApi


class TestNetworkfeesApi(unittest.TestCase):
    """NetworkfeesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NetworkfeesApi()

    def tearDown(self) -> None:
        pass

    def test_get_network_fees(self) -> None:
        """Test case for get_network_fees

        Get network fees
        """
        pass


if __name__ == '__main__':
    unittest.main()
