# coding: utf-8

"""
    LokoPay API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2024-08-22
    Contact: dev@lokopay.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from loko_client.models.create_customer_wallet_request import CreateCustomerWalletRequest

class TestCreateCustomerWalletRequest(unittest.TestCase):
    """CreateCustomerWalletRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateCustomerWalletRequest:
        """Test CreateCustomerWalletRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateCustomerWalletRequest`
        """
        model = CreateCustomerWalletRequest()
        if include_optional:
            return CreateCustomerWalletRequest(
                currency = 'BTC',
                network = '',
                customer = loko_client.models.payment_customer.PaymentCustomer(
                    id = '', 
                    email = '', 
                    ip_address = '', 
                    destination_address = '', 
                    destination_network = '', 
                    destination_currency = '', )
            )
        else:
            return CreateCustomerWalletRequest(
        )
        """

    def testCreateCustomerWalletRequest(self):
        """Test CreateCustomerWalletRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
