# coding: utf-8

"""
    LokoPay API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2024-08-22
    Contact: dev@lokopay.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from loko_client.api.payments_api import PaymentsApi


class TestPaymentsApi(unittest.TestCase):
    """PaymentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PaymentsApi()

    def tearDown(self) -> None:
        pass

    def test_cancel_payment(self) -> None:
        """Test case for cancel_payment

        Cancel payment
        """
        pass

    def test_confirm_payment(self) -> None:
        """Test case for confirm_payment

        Confirm payment
        """
        pass

    def test_create_payment(self) -> None:
        """Test case for create_payment

        Create a payment
        """
        pass

    def test_get_payment(self) -> None:
        """Test case for get_payment

        Get payment detail
        """
        pass

    def test_get_payments(self) -> None:
        """Test case for get_payments

        Get payments
        """
        pass

    def test_refund_payment(self) -> None:
        """Test case for refund_payment

        Refund payment
        """
        pass


if __name__ == '__main__':
    unittest.main()
