# coding: utf-8

"""
    LokoPay API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2024-08-22
    Contact: dev@lokopay.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from loko_client.models.crypto_currency import CryptoCurrency
from loko_client.models.payment_customer import PaymentCustomer
from loko_client.models.wallet_address import WalletAddress
from typing import Optional, Set
from typing_extensions import Self

class CustomerWallet(BaseModel):
    """
    CustomerWallet
    """ # noqa: E501
    id: Optional[StrictStr] = None
    object: Optional[StrictStr] = None
    object_secret: Optional[StrictStr] = None
    supported_cryptocurrencies: Optional[List[CryptoCurrency]] = None
    customer: Optional[PaymentCustomer] = None
    wallet_addresses: Optional[List[WalletAddress]] = None
    __properties: ClassVar[List[str]] = ["id", "object", "object_secret", "supported_cryptocurrencies", "customer", "wallet_addresses"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CustomerWallet from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in supported_cryptocurrencies (list)
        _items = []
        if self.supported_cryptocurrencies:
            for _item_supported_cryptocurrencies in self.supported_cryptocurrencies:
                if _item_supported_cryptocurrencies:
                    _items.append(_item_supported_cryptocurrencies.to_dict())
            _dict['supported_cryptocurrencies'] = _items
        # override the default output from pydantic by calling `to_dict()` of customer
        if self.customer:
            _dict['customer'] = self.customer.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in wallet_addresses (list)
        _items = []
        if self.wallet_addresses:
            for _item_wallet_addresses in self.wallet_addresses:
                if _item_wallet_addresses:
                    _items.append(_item_wallet_addresses.to_dict())
            _dict['wallet_addresses'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CustomerWallet from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "object": obj.get("object"),
            "object_secret": obj.get("object_secret"),
            "supported_cryptocurrencies": [CryptoCurrency.from_dict(_item) for _item in obj["supported_cryptocurrencies"]] if obj.get("supported_cryptocurrencies") is not None else None,
            "customer": PaymentCustomer.from_dict(obj["customer"]) if obj.get("customer") is not None else None,
            "wallet_addresses": [WalletAddress.from_dict(_item) for _item in obj["wallet_addresses"]] if obj.get("wallet_addresses") is not None else None
        })
        return _obj


