# coding: utf-8

"""
    LokoPay API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2024-08-22
    Contact: dev@lokopay.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class PaymentCustomer(BaseModel):
    """
    PaymentCustomer
    """ # noqa: E501
    id: Optional[StrictStr] = None
    email: Optional[StrictStr] = None
    ip_address: Optional[StrictStr] = None
    destination_address: Optional[StrictStr] = None
    destination_network: Optional[StrictStr] = None
    destination_currency: Optional[StrictStr] = None
    destination_address_type: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["id", "email", "ip_address", "destination_address", "destination_network", "destination_currency","destination_address_type"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PaymentCustomer from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PaymentCustomer from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "email": obj.get("email"),
            "ip_address": obj.get("ip_address"),
            "destination_address": obj.get("destination_address"),
            "destination_network": obj.get("destination_network"),
            "destination_currency": obj.get("destination_currency"),
            "destination_address_type": obj.get("destination_address_type")
        })
        return _obj

    @classmethod
    def set_destination_address_type(cls, destination_address_type: StrictStr) -> Self:
        """Set the destination address type"""
        return cls(destination_address_type=destination_address_type)


