# coding: utf-8

"""
    LokoPay API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2024-08-22
    Contact: dev@lokopay.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from loko_client.models.blockchain_transaction_detail import BlockchainTransactionDetail
from loko_client.models.destination_network_detail import DestinationNetworkDetail
from loko_client.models.payment_customer import PaymentCustomer
from loko_client.models.transfer_with_native_token import TransferWithNativeToken
from typing import Optional, Set
from typing_extensions import Self

class Payout(BaseModel):
    """
    Payout
    """ # noqa: E501
    id: Optional[StrictStr] = None
    object: Optional[StrictStr] = None
    amount: Optional[StrictStr] = None
    currency: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    customer: Optional[PaymentCustomer] = None
    destination_network_details: Optional[List[DestinationNetworkDetail]] = None
    blockchain_transaction_details: Optional[List[BlockchainTransactionDetail]] = None
    canceled_at: Optional[StrictInt] = None
    status: Optional[StrictStr] = None
    created_at: Optional[StrictInt] = None
    obj_secret: Optional[StrictStr] = None
    failed_reason: Optional[StrictStr] = None
    transfer_with_native_token: Optional[TransferWithNativeToken] = None
    __properties: ClassVar[List[str]] = ["id", "object", "amount", "currency", "description", "customer", "destination_network_details", "blockchain_transaction_details", "canceled_at", "status", "created_at", "obj_secret", "failed_reason", "transfer_with_native_token"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Payout from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of customer
        if self.customer:
            _dict['customer'] = self.customer.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in destination_network_details (list)
        _items = []
        if self.destination_network_details:
            for _item_destination_network_details in self.destination_network_details:
                if _item_destination_network_details:
                    _items.append(_item_destination_network_details.to_dict())
            _dict['destination_network_details'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in blockchain_transaction_details (list)
        _items = []
        if self.blockchain_transaction_details:
            for _item_blockchain_transaction_details in self.blockchain_transaction_details:
                if _item_blockchain_transaction_details:
                    _items.append(_item_blockchain_transaction_details.to_dict())
            _dict['blockchain_transaction_details'] = _items
        # override the default output from pydantic by calling `to_dict()` of transfer_with_native_token
        if self.transfer_with_native_token:
            _dict['transfer_with_native_token'] = self.transfer_with_native_token.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Payout from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "object": obj.get("object"),
            "amount": obj.get("amount"),
            "currency": obj.get("currency"),
            "description": obj.get("description"),
            "customer": PaymentCustomer.from_dict(obj["customer"]) if obj.get("customer") is not None else None,
            "destination_network_details": [DestinationNetworkDetail.from_dict(_item) for _item in obj["destination_network_details"]] if obj.get("destination_network_details") is not None else None,
            "blockchain_transaction_details": [BlockchainTransactionDetail.from_dict(_item) for _item in obj["blockchain_transaction_details"]] if obj.get("blockchain_transaction_details") is not None else None,
            "canceled_at": obj.get("canceled_at"),
            "status": obj.get("status"),
            "created_at": obj.get("created_at"),
            "obj_secret": obj.get("obj_secret"),
            "failed_reason": obj.get("failed_reason"),
            "transfer_with_native_token": TransferWithNativeToken.from_dict(obj["transfer_with_native_token"]) if obj.get("transfer_with_native_token") is not None else None
        })
        return _obj


