# coding: utf-8

"""
    LokoPay API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2024-08-22
    Contact: dev@lokopay.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from loko_client.models.get_network_fees200_response import GetNetworkFees200Response

from loko_client.api_client import ApiClient, RequestSerialized
from loko_client.api_response import ApiResponse
from loko_client.rest import RESTResponseType
import json

class WebhookEventApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client

    def retrieve(self, request_url, body_string, loko_signature):
        # 读取请求体
        if request_url is None or body_string is None or loko_signature is None:
            return None, "Invalid request"

        # 验证签名
        if not self.api_client.verify_signature(request_url, body_string, loko_signature):
            return None, "Invalid signature"

        try:
            # 解析 JSON
            webhook_event = json.loads(body_string)
        except json.JSONDecodeError as e:
            return None, str(e)

        return webhook_event, None
